### ISSUE TITLE
Problema de responsiveness en cucoders.dev/directorio/

### ISSUE THREAD

**Issue by CarlosZBent** [CuCodersCommunity/cucoderscommunity.github.io#101]
Hey! Me encontré este bug en la página del directorio de devs.

- Solo lo he encontrado en esa página
- El problema ocurre en el tamaño que en Tailwind corresponde a `sm`-`md`, o sea de 640px a 768px.

Al parecer el navBar se pasa de `width`, porque al inspeccionar el `body`, este aparece más pequeño que el navBar. Pero esto es solo una idea, vine a abrir el issue antes de intentar resolverlo.

Adjunto link a un video demostrando el bug 👇
- https://streamable.com/htmke1

**Comment by manuelernestog** [comment]
Interesting, lo estoy probando en chrome y hace bien los cambios. 

En que browser lo estás probando?

**Comment by CarlosZBent** [comment]
Aquí te dejo info de donde encontré esto

![image](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/72584905/bf44da52-90ff-4919-8152-ef642e3f4112)

Pero ahora probé en Chrome 114.0.5735.199 y Brave 1.22.71 y en ambos lo encontré. En Firefox Developer Edition v113.0b4 no sucede. 
Parece que tiene que ver con Chromium.

**Comment by manuelernestog** [comment]
En talla, ya pude replicarlo, le hecho un vistazo!

**Comment by manuelernestog** [comment]
Esto parece ser un problema en ese ambiente redimensionando la ventana con esa herramienta de Chromium.

Lo hice cambiando directamente el webview a la misma dimension y todo parece funcionar bien

![image](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/53962116/ac04a5dc-5bdf-4064-b8e8-22f4e0a8c3c5)
![Screenshot from 2023-07-29 11-59-24](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/53962116/faeb5b47-fa62-46cd-9ee5-668efc536a1b)
En estos dos escenarios las ventanas tiene 821 píxeles y en uno se ve bien y en otro no.

Estuve inspeccionando el código y hace algo raro con el modelo de caja en la versión que se ve mal que parece ser algun problema con el render de la vista. 

Por ahora y con esto voy a cerrar el Issue, si aparece nuevamente este problema en un navegador miesntras se esta renderizando la vista y no en este modo desarrollo entonces lo atendemos
