### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by jjavierdguezas** [CuCodersCommunity/cucoderscommunity.github.io#104]
Hola, primero que todo genial idea esta de `CuCoders` 💪🏻 aunque ya no estoy en Cuba, aprecio mucho este tipo de iniciativas

He visto en varias partes de la UI algunos errores ortográficos, la mayoría son cosas sencillas como tildes, letras cambiadas, etc que son fáciles de arreglar. Entiendo que la parte de blogs, post de empleos, etc es muy difícil corregir en la práctica, pero los elementos de la UI de `CuCoders` debería estar bien (lo que está ahora y lo que vendrá a futuro)

Recomendaría hacerle una revisión exhaustiva al sitio y arreglar este tipo de cosas, además de instalar esta extensión de vscode que me ha sido muy útil en este sentido [Code Spell Checker](https://github.com/streetsidesoftware/vscode-spell-checker). La extensión no es perfecta, pero ayuda bastante y tiene varios diccionarios. (con solo esta extensión he podido corregir faltas en 27 archivos que luego haré PR para contribuir en su corrección)

**Comment by manuelernestog** [comment]
Genial. Mil gracias por la contribución Javier 🙏🙌
