### ISSUE TITLE
Tipografia blanca en modo oscuro.

### ISSUE THREAD

**Issue by qvacode** [CuCodersCommunity/cucoderscommunity.github.io#112]
Contexto: Por defecto, en las secciones de cv y servicios, en modo oscuro la tipografia se ve en negro.

Como un usuario: Quiero que la tipografia se adapte al cambiar de tema blanca en modo oscuro y negra en modo claro.

    Adicionar los estilos pertinentes en la UI para la tipografia en el modo oscuro

![Captura de pantalla de 2023-09-17 22-19-15](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/71405558/e2d27bd8-9720-4502-a0aa-fc80b171439d)

**Comment by manuelernestog** [comment]
Fixed and deployed!
