### ISSUE TITLE
Mi perfil no se muestra en la plataforma

### ISSUE THREAD

**Issue by mnicolas94** [CuCodersCommunity/cucoderscommunity.github.io#113]
Hola, hace unos meses creé mi perfil como desarrollador en la plataforma pero no aparece. Ya pertenezco a la organización aquí en github e incluso puedo editar el perfil en la web. No sé si me salté algún paso o mi perfil en github tiene algún problema. Gracias de antemano.

**Comment by manuelernestog** [comment]
Hola @mnicolas94 disculpa la demora de la respuesta, no había tenido tiempo de sentarme a revisar que estaba pasando. Era un problema en la API de miembros que no se estaba ejecutando el worker que la maneja. Ya debe aparecer sin problemas 

https://cucoders.dev/dev/mnicolas94/
