### ISSUE TITLE
Fecha de publicación de la oferta

### ISSUE THREAD

**Issue by maplop** [CuCodersCommunity/cucoderscommunity.github.io#141]
![Sin título](https://github.com/user-attachments/assets/28f353c0-3130-4fdd-8052-e24e9788e193)
-Seria bueno que cada oferta tuviese la fecha de publicación visible (cualquiera de las dos opciones en la foto adjunta) en la vista miniatura esto ahorraría tiempo de búsqueda

**Comment by manuelernestog** [comment]
Buena sugerencia esta!  Gracias @maplop
