### ISSUE TITLE
Descripción de los artículos en las tarjetas de la vista principal está mostrando un formato inadecuado

### ISSUE THREAD

**Issue by manuelernestog** [CuCodersCommunity/cucoderscommunity.github.io#42]
Las tarjetas de la vista principal muestran una descripción que puede ser introducida por el usuario y en caso de no hacerlo, toma el texto del artículo y lo utiliza como descripción. 

Si el texto contiene elementos MD está mostrando en la descripción de las tarjetas en la vista principal el texto Raw.

![image](https://user-images.githubusercontent.com/53962116/221391765-04715aa7-7310-4a9d-b31a-dd840773534c.png)

## Criterios de aceptación:

El texto debe mostrarse como sin los elementos especiales del formato markdown en la descripción de la tarjeta.

## Notas para el dev

- El componente a solucionar es `src/components/blogCard.astro`
- Astro cuenta con diferentes helpers que pueden ser de utilidad
- Revisar tambien la lib marked que ya esta instalada que se utiliza para el trabajo con markdown

**Comment by CarlosZBent** [comment]
@manuelernestog me puedes asignar este a mí y empiezo a trabajar en él

**Comment by CarlosZBent** [comment]
### Posible solución

@manuelernestog ¿esto sería una solución aceptable?

Aquí lo que hace es que renderiza el markdown en la propia descripción del post.

![image](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/72584905/7c203d2a-b297-4493-a634-c50baa469a14)

**Comment by manuelernestog** [comment]
@CarlosZBent en este caso lo ideal sería que no se aplicara como tal el estilo. Es decir que procesara el texto a texto plano. Si le aplicamos el markdown entonces puede que se cuele un link o esas negritas en la descripción de la tarjeta que no encajan con el estilo como tal del de la vista.

**Comment by manuelernestog** [comment]
@CarlosZBent  Ya te la asigne el issue, si tienes algún bateo o algo de eso me dices sin lio. Igual que te lo haya asignado no es una obligacion si te enredas o no tienes tiempo o algo no hay lio. Estas cosas normalmente no se asignan a no ser que se tenga un core team trabajando en la solucion.

**Comment by manuelernestog** [comment]
Solucionando en #91 Nice work @CarlosZBent 🙌🙌
