### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by manuelernestog** [CuCodersCommunity/cucoderscommunity.github.io#93]
CuCoders esta implementado con TailwindCCS utilizando la lib de UI [Flowbite](https://flowbite.com/).

**Contexto**:Por defecto, la mayoría de los componentes ya contienen los estilos integrados para utilizar el modo oscuro, pero de manera general la interfaz no los contiene y algunos elementos que se hicieron a mano tampoco lo tiene implementado.

**Como un usuario**: Quiero ser capaz de cambiar a modo oscuro la aplicación.

- Adicionar los estilos pertinentes en la UI para el modo oscuro
- Crear un icono toggle para alternar entre modo claro y oscuro.
- Almacenar en el localstore del navegador el modo configurado

Para la creación del modo oscuro se debe seguir con la paleta de colores seleccionada por flowbite para el modo oscuro, así como el mismo sistema que proponen para hacer el cambio.

**Información útil**:

https://flowbite.com/docs/customize/dark-mode/

**Comment by CarlosZBent** [comment]
working on it... 👨‍🔧

**Comment by manuelernestog** [comment]
Ufffff brutal bro 🚀🚀🚀

**Comment by CarlosZBent** [comment]
@manuelernestog ¿El toggle para el modo oscuro debe ser visible también en la vista mobile, o solo en la vista desktop?

En mi opinión sería mejor que en modo mobile tome el theme del telefóno automáticamente

**Comment by manuelernestog** [comment]
@CarlosZBent que la web sea capaz de tomar el que tiene el sistema por defecto se agradece pero si es importante que el usuario siempre tenga la libertad de seleccionar la opcion que desee.

Para la vista de teléfono se puede poner como una opción más en el sidebar como por ejemplo lo hace telegram

![image](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/53962116/44b9ca25-b79a-4ac4-a8e1-7ac304082b28)

De hecho en la vista de desktop para no sobrecargar la barra creo que tambien seria bueno ponerlo en el menu que se despliega.

Sobre el logo creo que la opción del svg quizas es la más sencilla.

**Comment by manuelernestog** [comment]
@CarlosZBent por aca te dejo un svg del logo

https://drive.google.com/file/d/1fSeVZHXo8zf3YMVQIGO1OkkDBX1flL4G/view?usp=sharing

En caso de que tengas problemas para alternar el color siempre se puede optar por utilizar las imágenes normales

**Comment by CarlosZBent** [comment]
@manuelernestog esto está prácticamente al 100. Voy a consultar aquí unos detalles que creo que sería mejor arreglarlos sobre la marcha después de ya implementar el modo oscuro.

1. Los campos de categories en páginas como nueva-app o nuevo-empleo:
![new app categories](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/72584905/a39a60c1-adfc-4f6a-9538-670adea32aab)
Tienen un sistema de clases un poco raro que solo se ve en las DevTools en el navegador y no en el código en sí mismo, y por mucho que le he dado no he podido hacer que funcionen con el modo oscuro, curiosamente, sí funcionan en la página de nuevo-recurso.

2. Los icons del footer mobile. Hay tres opciones: hacerlos SVG inline en vez de una etiqueta `<img/>` y manipular el atributo fill para cambiar el color; darles un color que sirva tanto para modo claro como oscuro (eg. *fill-gray-500*); o en el modo oscuro darles un background que los haga resaltar. 
Intenté las dos primeras y no funcionó porque el SVG que envía a la página de empleos (`/assets/img/icons/briefcase-line.svg`) no es un outline como el resto, sino que tiene un background, y cambiar el *fill* cambia el background y no el outline del ícono. Entonces me fui por la tercera opción.
![image](https://github.com/CuCodersCommunity/cucoderscommunity.github.io/assets/72584905/2073934a-1d7a-4182-8c66-d9431f19e14c)

Esas son las dos cosas que más resaltan y quería consultar antes de hacer pull request, fuera de eso todo está bastante estándar. Podemos hacer una revisión si quieres para limar detalles.

**Comment by manuelernestog** [comment]
@CarlosZBent jone asere eso te va quedando volaisimooooo 🤩🤩🤩

- Esos select lo que les pasa es que se construyen en la vista con JS con una lib y lo que hacemos es sobreescribirlos con css y unos selectores.

Los estilos están acá `src/styles/main.css`

Creo que lo más sencillo aquí es tomar los estilos que le asigna tailwind a un select normal como el que encontramos en la vista de adicionar nuevo recurso http://localhost:3000/nuevo-recurso, inspeccionarlo con el navegador y extraer los estilos con los colores y tal que necesitamos para conseguir el estilo del componente oscuro, ya luego en main.css creamos una regla para cuando es modo oscuro le metemos esos estilos y pan ya.

En cualquier caso, si te enredas con eso me lo dejas ahí sin lio.

- Sobre los iconos del footer, la tercera opción me parece válida, pero podemos utilizar una opción un poco más elegante para manipular las imágenes con los filtros de HTML (para lograr otro color es un quilo con esto, pero en este caso moviendo contraste e invirtiendo debe quedar bastante bien)

Algo así

```html
  <a href="/"> 
    <img src="/assets/img/icons/outline-home.svg" class="h-7 w-7 m-3 dark:invert dark:contrast-150" alt="Inicio" />
  </a>
```

Si tienes alguna otra duda o algo, tira para acá 🙌

**Comment by manuelernestog** [comment]
🤔🤔 que raro que quedo dorado eso, en teoría, debió haber quedado normal de todas formas, no importa, si quieres dejarlo así y cuando hagas el PR le echo un looking a ver que le paso que no quedo blanco

**Comment by CarlosZBent** [comment]
@manuelernestog `tomselect.css` me está volviendo loco para el modo prieto, así que voy a hacer la PR para no seguir demorando la feature. Si este tema de tomselect lo haces un issue después, ayudaré también. 

Buscando y buscando encontré [esta discusión](https://github.com/orchidjs/tom-select/discussions/160) donde alguien pregunta sobre modo oscuro para tomselect + tailwind pero no tiene respuesta.

**Comment by CarlosZBent** [comment]
@manuelernestog sobre los íconos del footer:

Salen dorados pq el `fill` de los archivos SVG no es negro (#000), es un gris oscuro (#334155), entonces lo opuesto no es blanco sino dorado.

Cuando se les pone #000 de `fill`, invert y contrast los vuelven blancos

¿Les pongo el `fill` en #000 a esos SVG para que se vuelvan blancos con `dark:invert`?

**Comment by manuelernestog** [comment]
@CarlosZBent  Podríamos hacerlo, aunque creo que se va a ver muy oscuro en el modo claro. Si quieres le podemos adicionar la clase `saturate-0` que también trabaja con los filtros css y le mata la saturación y subirle el contraste en vez de 150 a 200 para que se vea más blanco.
